apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: springbootdocker  #Your app's name
spec:
 replicas: 1
 template:
  metadata:
    labels:
      app: springbootdocker
  spec:
   volumes:
    - name: spanner-creds
      secret:
       secretName: spanner-secret
   containers:
   - name: springbootdocker  #Your app will be the running container you built
     image: gcr.io/utility-axis-208712/springbootdocker:v2
     ports:
      - containerPort: 8080
        name: springboot
     env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secrets/app-secrets/ci-cd.json
     volumeMounts:
      - name: spanner-creds
        mountPath: /secrets/app-secrets
        readOnly: true
     imagePullPolicy: Always
---
kind: Service
apiVersion: v2
metadata:
 name: springbootdocker  #This will be the name of your load balancer
spec:
 selector:
  app: springbootdocker  #The load balancer will be attached to the app you specify by name here
 ports:
 - protocol: TCP
   port: 80
   targetPort: 8080
 type: LoadBalancer
 loadBalancerSourceRanges:  #Firewall rules
    - 151.140.0.0/16
    - 165.130.0.0/16
    - 207.11.0.0/17
    - 50.207.27.182/32
    - 98.6.11.8/29